build-and-push:
  image: docker:latest
  services:
    - docker:dind
  script:
    - docker login -u $DOCKER_LOGIN -p $DOCKER_TOKEN
    - docker build -t mmerian/lilypond .
    - docker push mmerian/lilypond